# Generated by Django 3.2.8 on 2021-12-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.TextField(default='', verbose_name='ID пользователя в соц сети'),
        ),
    ]
